---
# This file is not managed by doco-cd because it can't manage itself

secrets:
  1pw_token:
    file: /opt/doco-cd/1pw_token
  api_secret:
    file: /opt/doco-cd/api_secret
  webhook_secret:
    file: /opt/doco-cd/webhook_secret
services:
  app:
    container_name: doco-cd
    environment:
      API_SECRET_FILE: /run/secrets/api_secret
      DEPLOY_CONFIG_BASE_DIR: ./docker/vps-pangolin/
      HTTP_PORT: 8880
      LOG_LEVEL: info
      POLL_CONFIG: |-
        - url: https://github.com/bjw-s-labs/home-ops.git
          reference: main
          interval: 3600
      SECRET_PROVIDER: 1password
      SECRET_PROVIDER_ACCESS_TOKEN_FILE: /run/secrets/1pw_token
      TZ: Europe/Amsterdam
      WEBHOOK_SECRET_FILE: /run/secrets/webhook_secret
    healthcheck:
      test:
        - CMD
        - /doco-cd
        - healthcheck
      start_period: 15s
      interval: 30s
      timeout: 5s
      retries: 3
    image: ghcr.io/kimdre/doco-cd:0.82.2@sha256:b3e3c28c7690e1f3cb7ad5cdbf2cecf34965a40ef3e89bf55bb21f221f1c0a20
    ports:
      - 8880:8880
    restart: unless-stopped
    secrets:
      - 1pw_token
      - api_secret
      - webhook_secret
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
volumes:
  data: {}
networks:
  default:
    name: pangolin
    external: true
