---
# This file is not managed by doco-cd because it can't manage itself

secrets:
  1pw_token:
    file: /opt/doco-cd/1pw_token
services:
  app:
    configs:
      - source: poll-config.yml
        target: /poll-config.yml
    container_name: doco-cd
    environment:
      HTTP_PORT: 8080
      LOG_LEVEL: info
      POLL_CONFIG: |-
        - run_once: true
          url: https://github.com/bjw-s-labs/home-ops.git
      SECRET_PROVIDER: 1password
      SECRET_PROVIDER_ACCESS_TOKEN_FILE: /run/secrets/1pw_token
      DEPLOY_CONFIG_BASE_DIR: ./docker/vps-pangolin/
    healthcheck:
      test:
        - CMD
        - /doco-cd
        - healthcheck
      start_period: 15s
      interval: 30s
      timeout: 5s
      retries: 3
    image: ghcr.io/kimdre/doco-cd:0.72.2@sha256:14997f07cc2fea4e7a95d1ab8db66210f4ac2961cd3d0ed5be44c8af808d1dd9
    ports:
      - 8080:8080
    restart: unless-stopped
    secrets:
      - 1pw_token
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
volumes:
  data: {}
