---
# This file is not managed by doco-cd because it can't manage itself

secrets:
  1pw_token:
    file: /opt/doco-cd/1pw_token
services:
  app:
    container_name: doco-cd
    environment:
      DEPLOY_CONFIG_BASE_DIR: ./docker/vps-pangolin/
      LOG_LEVEL: info
      POLL_CONFIG: |-
        - url: https://github.com/bjw-s-labs/home-ops.git
          reference: main
          interval: 3600
      SECRET_PROVIDER: 1password
      SECRET_PROVIDER_ACCESS_TOKEN_FILE: /run/secrets/1pw_token
      TZ: Europe/Amsterdam
    healthcheck:
      test:
        - CMD
        - /doco-cd
        - healthcheck
      start_period: 15s
      interval: 30s
      timeout: 5s
      retries: 3
    image: ghcr.io/kimdre/doco-cd:0.75.0@sha256:29833479e74952aa8d2535edcda66dbb7161e38378a6b2a3adeb73f142444440
    restart: unless-stopped
    secrets:
      - 1pw_token
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
volumes:
  data: {}
