---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: llmkube
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: llmkube
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: llmkube
      namespace: ai
  interval: 1h
  path: "./kubernetes/apps/ai/llmkube/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: ai
  timeout: 5m
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: llmkube-models
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: llmkube-models
  dependsOn:
    - name: llmkube
      namespace: ai
  interval: 1h
  path: "./kubernetes/apps/ai/llmkube/models"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: ai
  timeout: 5m
