---
working_dir: ./docker/icarus
auto_discover: true
auto_discover_opts:
  depth: 1
  delete: true
external_secrets:
  VPS_IP: "op://automation/towonel-tunnel/ip"
  TOWONEL_ACME_EMAIL: "op://automation/towonel-tunnel/acme_email"
  TOWONEL_INVITE_HASH_KEY: "op://automation/towonel-tunnel/invite_hash_key"
  RATHOLE_FORGEJO_SSH_TOKEN: "op://automation/rathole/forgejo_ssh_token"
force_recreate: false
reconciliation:
  enabled: true
  interval: 3600
