---
working_dir: ./docker/icarus
auto_discovery:
  enabled: true
  depth: 1
  delete: true
external_secrets:
  GATUS_PUSHOVER_TOKEN: op://Docker/Pushover - Gatus/password
  GATUS_PUSHOVER_KEY: op://Infrastructure - Automation/Pushover/userkey_bernd
  GATUS_REMOTE_DDNS_HOSTNAME: op://Infrastructure - Automation/Gatus/home_heartbeat_ddns_hostname
  GATUS_REMOTE_HEARTBEAT_TOKEN: op://Infrastructure - Automation/Gatus/icarus_home_heartbeat_token
  CADDY_ACME_EMAIL: op://Docker/Icarus - ACME/username
force_recreate: false
reconciliation:
  enabled: true
  interval: 3600
