# Warning, this file is autogenerated by nix4vscode. Don't modify this manually.

{ pkgs }:

let
  vscode-utils = pkgs.vscode-utils;
in
{
  "ms-python"."python" = vscode-utils.extensionFromVscodeMarketplace {
    name = "python";
    publisher = "ms-python";
    version = "2023.20.0";
    sha256 = "1qvpqs7mc5k6ldp9az1bqgfwl6hs0nk1wzwp3fdaqmm1vpg0662b";
  };

  "ms-python"."vscode-pylance" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-pylance";
    publisher = "ms-python";
    version = "2023.11.10";
    sha256 = "1i2xywjw4dghw0bbgk2z90zhgiy7sxdl4yv88399shjwyvbp2psf";
  };

  "esbenp"."prettier-vscode" = vscode-utils.extensionFromVscodeMarketplace {
    name = "prettier-vscode";
    publisher = "esbenp";
    version = "10.1.0";
    sha256 = "01s0vi2h917mqfpdrhqhp2ijwkibw95yk2js0l587wvajbbry2s9";
  };

  "eamodio"."gitlens" = vscode-utils.extensionFromVscodeMarketplace {
    name = "gitlens";
    publisher = "eamodio";
    version = "14.5.1";
    sha256 = "05kz3mqf80bdb98ngl7kr6yqhy22vg583z9if0ndy0xriwa036gz";
  };

  "ms-vscode-remote"."remote-containers" = vscode-utils.extensionFromVscodeMarketplace {
    name = "remote-containers";
    publisher = "ms-vscode-remote";
    version = "0.321.0";
    sha256 = "0p96z70nfzw829hijqcnw76b2pdn09j5rzhkhxqzvb9hla9f414n";
  };

  "ms-vscode-remote"."remote-ssh" = vscode-utils.extensionFromVscodeMarketplace {
    name = "remote-ssh";
    publisher = "ms-vscode-remote";
    version = "0.107.1";
    sha256 = "1q9xp8id9afhjx67zc7a61zb572f296apvdz305xd5v4brqd9xrf";
  };

  "redhat"."vscode-yaml" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-yaml";
    publisher = "redhat";
    version = "1.14.0";
    sha256 = "0pww9qndd2vsizsibjsvscz9fbfx8srrj67x4vhmwr581q674944";
  };

  "golang"."go" = vscode-utils.extensionFromVscodeMarketplace {
    name = "go";
    publisher = "golang";
    version = "0.40.0";
    sha256 = "1k2zv49pam436cgvb970dc9n4xpdkd07lp8jllrsx5vnx7m2ml52";
  };

  "gruntfuggly"."todo-tree" = vscode-utils.extensionFromVscodeMarketplace {
    name = "todo-tree";
    publisher = "gruntfuggly";
    version = "0.0.226";
    sha256 = "0yrc9qbdk7zznd823bqs1g6n2i5xrda0f9a7349kknj9wp1mqgqn";
  };

  "ms-kubernetes-tools"."vscode-kubernetes-tools" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-kubernetes-tools";
    publisher = "ms-kubernetes-tools";
    version = "1.3.15";
    sha256 = "1x6npc90p6b1wx5sd1hd0x0djahmffr6lw9cxh2zg10rbpq48w8i";
  };

  "hashicorp"."terraform" = vscode-utils.extensionFromVscodeMarketplace {
    name = "terraform";
    publisher = "hashicorp";
    version = "2.29.0";
    sha256 = "tGBs7+5ho+mvcJQF5gi/XfoiJ70MuCtFFOiPi2baae8=";
  };

  "ionutvmi"."path-autocomplete" = vscode-utils.extensionFromVscodeMarketplace {
    name = "path-autocomplete";
    publisher = "ionutvmi";
    version = "1.25.0";
    sha256 = "0jjqh3p456p1aafw1gl6xgxw4cqqzs3hssr74mdsmh77bjizcgcb";
  };

  "tamasfe"."even-better-toml" = vscode-utils.extensionFromVscodeMarketplace {
    name = "even-better-toml";
    publisher = "tamasfe";
    version = "0.19.2";
    sha256 = "0q9z98i446cc8bw1h1mvrddn3dnpnm2gwmzwv2s3fxdni2ggma14";
  };

  "redhat"."ansible" = vscode-utils.extensionFromVscodeMarketplace {
    name = "ansible";
    publisher = "redhat";
    version = "2.9.118";
    sha256 = "0yndj2r0w2zxc5firxgfrykkc5ajy9gsmrfmkz80kfhwk33n9y1p";
  };

  "fnando"."linter" = vscode-utils.extensionFromVscodeMarketplace {
    name = "linter";
    publisher = "fnando";
    version = "0.0.19";
    sha256 = "13bllbxd7sy4qlclh37qvvnjp1v13al11nskcf2a8pmnmj455v4g";
  };

  "catppuccin"."catppuccin-vsc" = vscode-utils.extensionFromVscodeMarketplace {
    name = "catppuccin-vsc";
    publisher = "catppuccin";
    version = "3.7.1";
    sha256 = "0428lvmsy5idfk9zqx8xak8b7d86vxzlg59y31d0n5sds2xj2lq5";
  };

  "catppuccin"."catppuccin-vsc-icons" = vscode-utils.extensionFromVscodeMarketplace {
    name = "catppuccin-vsc-icons";
    publisher = "catppuccin";
    version = "0.30.0";
    sha256 = "035rl1kx565h9s0xlh20pr6p26g9g9zy2l4zag0bn653lbm51jhg";
  };

  "jnoortheen"."nix-ide" = vscode-utils.extensionFromVscodeMarketplace {
    name = "nix-ide";
    publisher = "jnoortheen";
    version = "0.2.2";
    sha256 = "1264027sjh9a112si0y0p3pk3y36shj5b4qkpsj207z7lbxqq0wg";
  };

  "signageos"."signageos-vscode-sops" = vscode-utils.extensionFromVscodeMarketplace {
    name = "signageos-vscode-sops";
    publisher = "signageos";
    version = "0.8.0";
    sha256 = "1mjvlv3yr2ilyki5ydj8kn851rr1lmf05rm9rkv8dihhyqmdpiid";
  };

  "elagil"."pre-commit-helper" = vscode-utils.extensionFromVscodeMarketplace {
    name = "pre-commit-helper";
    publisher = "elagil";
    version = "0.4.3";
    sha256 = "1877k35biy72sh0c5f890z0mh36sr2cvd3d1mmw9mb2mdfq6xyqk";
  };
}
