---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: forgejo-redis
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: forgejo-redis
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: forgejo-redis
      namespace: dev
  interval: 1h
  path: "./kubernetes/apps/dev/forgejo/redis"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: dev
  timeout: 5m
---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: forgejo
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: forgejo
  components:
    - ../../../../components/volsync
    - ../../../../components/anubis
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: forgejo-redis
      namespace: dev
  interval: 1h
  path: "./kubernetes/apps/dev/forgejo/app"
  postBuild:
    substitute:
      APP: forgejo
      APP_UID: "1000"
      APP_GID: "1000"
      VOLSYNC_CAPACITY: 10Gi
      ANUBIS_TARGET: http://forgejo-http.dev.svc.cluster.local:3000
      ANUBIS_MEM_LIMIT: 384Mi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: dev
  timeout: 5m
  wait: false
---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: forgejo-runner
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: forgejo
  interval: 1h
  path: "./kubernetes/apps/dev/forgejo/runner"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: dev
  timeout: 5m
  wait: false
