---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kopiur.home-operations.com/snapshotpolicy_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotPolicy
metadata:
  name: ${APP}
  annotations:
    kopiur.home-operations.com/allow-identity-change: "true"
spec:
  mover:
    cache:
      capacity: ${KOPIUR_CAPACITY:=5Gi}
      mode: Ephemeral
      storageClassName: miroir-local
    securityContext:
      runAsUser: ${KOPIUR_MOVER_UID:=2000}
      runAsGroup: ${KOPIUR_MOVER_GID:=2000}
  repository:
    kind: ClusterRepository
    name: nas
  retention:
    keepDaily: 7
    keepHourly: 24
  sources:
    - pvc:
        name: "${KOPIUR_CLAIM:-${APP}}"
  verification:
    deep:
      schedule:
        cron: H 5 1 * *
    quick:
      schedule:
        cron: H 3 * * *
  volumeSnapshotClassName: ${KOPIUR_SNAPSHOTCLASS:=miroir-snap}
