---
name: frr
services:
  frr:
    container_name: frr
    image: quay.io/frrouting/frr:10.7.1
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - NET_BIND_SERVICE
      - SYS_ADMIN
    network_mode: host
    volumes:
      - ./config/daemons:/etc/frr/daemons:ro
      - ./config/frr.conf:/etc/frr/frr.conf:ro
