---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: alertmanager-secret
    creationPolicy: Owner
    template:
      data:
        pushover_api_token: "{{ .pushover_alertmanager_token }}"
        pushover_api_userkey: "{{ .pushover_userkey_bernd }}"
        icarus_home_heartbeat_token: "{{ .gatus_icarus_home_heartbeat_token }}"
        icarus_home_heartbeat_url: "https://{{ .gatus_icarus_gatus_hostname }}/api/v1/endpoints/home_heartbeat/external?success=true"
  dataFrom:
    - extract:
        key: Pushover
      rewrite:
        - regexp:
            source: "(.*)"
            target: "pushover_$1"
    - extract:
        key: gatus
      rewrite:
        - regexp:
            source: "(.*)"
            target: "gatus_$1"
