---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pangolin-operator
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: pangolin-operator
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: pangolin-operator
      namespace: network
  interval: 1h
  path: "./kubernetes/apps/network/pangolin-operator/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: network
  timeout: 5m
---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pangolin-operator-config
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: multus
  dependsOn:
    - name: pangolin-operator
      namespace: network
  healthChecks:
    - apiVersion: pangolin.home-operations.com/v1alpha1
      kind: NewtSites
      name: homelab
  interval: 1h
  path: "./kubernetes/apps/network/pangolin-operator/config"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
