---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: pangolin
spec:
  endpoints:
    - dnsName: ingress-ext.bjw-s.dev
      recordType: A
      targets:
        - 135.125.53.129
    - dnsName: pangolin.bjw-s.dev
      recordType: A
      targets:
        - 135.125.53.129
