---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: newt
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: newt-secret
    creationPolicy: Owner
    template:
      data:
        NEWT_ID: "{{ .pangolin_newt_id }}"
        NEWTSC_SITE_NICEID: "{{ .pangolin_newt_site_niceid }}"
        NEWT_SECRET: "{{ .pangolin_newt_secret }}"
        NEWT_SERVER_URL: "{{ .pangolin_hostname }}"
  dataFrom:
    - extract:
        key: Pangolin
      rewrite:
        - regexp:
            source: "[^a-zA-Z0-9-]"
            target: "_"
        - regexp:
            source: "(.*)"
            target: "pangolin_$1"
