---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: newt
spec:
  chartRef:
    kind: OCIRepository
    name: newt
  interval: 30m
  values:
    global:
      deploymentAnnotations:
        reloader.stakater.com/auto: "true"
      image:
        # renovate: datasource=github-releases depName=fosrl/newt
        tag: 1.10.3
      nativeMode:
        enabled: false
      networkPolicy:
        enabled: false
      prometheusRule:
        enabled: true
    newtInstances:
      - name: main-tunnel
        enabled: true
        replicas: 1
        pingInterval: 60s
        interface: "newt"
        useNativeInterface: false
        acceptClients: true
        mtu: 1380
        auth:
          existingSecretName: newt-secret
        extraEnv:
          BLUEPRINT_FILE: /etc/newt/blueprint.yaml
          NEWT_ADMIN_ADDR: "0.0.0.0:2112"
          NEWT_METRICS_PROMETHEUS_ENABLED: "true"
        extraVolumeMounts:
          - name: blueprint
            mountPath: /etc/newt
        extraVolumes:
          - name: blueprint
            emptyDir: {}
        initContainers:
          - name: newt-sidecar
            image: ghcr.io/home-operations/newt-sidecar:0.2.1
            args:
              - --enable-service
            env:
              - name: NEWTSC_SITE_ID
                valueFrom:
                  secretKeyRef:
                    name: newt-secret
                    key: NEWTSC_SITE_ID
              - name: NEWTSC_DENY_COUNTRIES
                value: RU,CN,KP,IR,BY,IL
              - name: NEWTSC_GATEWAY_NAME
                value: envoy-external
              - name: NEWTSC_TARGET_HOSTNAME
                value: envoy-external.network.svc.cluster.local
            restartPolicy: Always
            resources:
              limits:
                memory: 128Mi
            volumeMounts:
              - name: blueprint
                mountPath: /etc/newt
          - name: wait-blueprint
            image: ghcr.io/home-operations/busybox:1.37.0
            command:
              - /bin/sh
              - -c
              - until test -f /etc/newt/blueprint.yaml; do sleep 1; done
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 16Mi
            volumeMounts:
              - name: blueprint
                mountPath: /etc/newt
        metrics:
          port: 2112
          service:
            enabled: true
            port: 2112
          serviceMonitor:
            enabled: true
        service:
          enabled: true
    rbac:
      clusterRole: true
    serviceAccount:
      automountServiceAccountToken: true
      name: newt
