---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
components:
  - ../../components/flux-alerts
  - ../../components/kopiur/secret
  - ../../components/namespace
patches:
  - target:
      kind: Namespace
    patch: |
      - op: add
        path: /metadata/annotations/kopiur.home-operations.com~1privileged-movers
        value: "true"
      - op: add
        path: /metadata/labels
        value:
          resource.kubernetes.io/admin-access: "true"
resources:
  - ./audiobookshelf/ks.yaml
  - ./bonob/ks.yaml
  - ./bookboss/ks.yaml
  - ./dispatcharr/ks.yaml
  - ./jellyfin/ks.yaml
  - ./maintainerr/ks.yaml
  - ./navidrome/ks.yaml
