[env]
JUST_UNSTABLE = "1"
FLATE_PATH = '{{config_root}}/kubernetes/flux/cluster'
KUBECONFIG = '{{config_root}}/kubeconfig'
MINIJINJA_CONFIG_FILE = "{{config_root}}/.minijinja.toml"
TALOSCONFIG = '{{config_root}}/talosconfig'

[settings]
pipx.uvx = true

[tools]
"aqua:astral-sh/uv" = "latest"
"aqua:cilium/hubble" = "latest"
"aqua:cli/cli" = "latest"
"aqua:google/yamlfmt" = "latest"
"aqua:helmfile/helmfile" = "latest"
"aqua:mitsuhiko/minijinja" = "latest"
"aqua:rhysd/actionlint" = "latest"
"github:home-operations/flate" = "latest"
"github:kguardian-dev/kguardian" = { version = "latest", version_prefix = "advisor/v", exe = "advisor", bin = "kubectl-kguardian" }
"pipx:ansible" = "latest"
"pipx:ansible-core" = "latest"
"talosctl" = "v1.14.0-rc.2"

[hooks]
postinstall = "ansible-galaxy install -r {{config_root}}/ansible/requirements.yaml"
