[env]
JUST_UNSTABLE = "1"
KUBECONFIG = '{{config_root}}/kubeconfig'
MINIJINJA_CONFIG_FILE = "{{config_root}}/.minijinja.toml"
TALOSCONFIG = '{{config_root}}/talosconfig'

[settings]
pipx_uvx = true

[tools]
"aqua:astral-sh/uv" = "latest"
"aqua:google/yamlfmt" = "latest"
"pipx:flux-local" = "latest"
"pipx:ansible" = "latest"
"pipx:ansible-core" = "latest"

[hooks]
postinstall = "ansible-galaxy install -r {{config_root}}/ansible/requirements.yaml"
