---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Labeler

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Labeler
        uses: https://github.com/actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6.0.1
        with:
          configuration-path: .forgejo/labeler.yaml
