---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Image Pull

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ forgejo.workflow }}-${{ forgejo.event.number || forgejo.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  filter-changes:
    name: Filter changes
    runs-on: ubuntu-latest
    outputs:
      changed-files: ${{ steps.changed-files.outputs.changed_files }}
    steps:
      - name: Get changed files
        id: changed-files
        uses: https://github.com/bjw-s-labs/action-changed-files@a9a36fb08ce06db9b02fbd8026cc2c0945eb9841 # v0.6.0
        with:
          patterns: |-
            kubernetes/**/*

  extract-images:
    if: ${{ needs.filter-changes.outputs.changed-files != '[]' }}
    name: Extract Images (${{ matrix.branches }})
    runs-on: ubuntu-latest
    needs:
      - filter-changes
    strategy:
      matrix:
        branches:
          - default
          - pull
      fail-fast: false
    outputs:
      default: ${{ steps.extract-images.outputs.default }}
      pull: ${{ steps.extract-images.outputs.pull }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: "${{ matrix.branches == 'default' && github.event.repository.default_branch || '' }}"
          persist-credentials: false

      - name: Gather Images
        shell: bash
        run: |-
          flux-local get cluster \
            --all-namespaces \
            --path kubernetes/flux/cluster \
            --enable-images \
            --only-images \
            --output json \
            --output-file images.json

      - name: Extract Images
        id: extract-images
        run: |
          echo "${{ matrix.branches }}=$(jq --compact-output '.' images.json)" >> "${FORGEJO_OUTPUT}"

  diff:
    name: Compare Images
    runs-on: ubuntu-latest
    needs:
      - extract-images
    outputs:
      images: ${{ steps.diff.outputs.images }}
    steps:
      - name: Compare Images
        id: diff
        run: |
          images=$(jq --compact-output --null-input \
              --argjson f1 '${{ needs.extract-images.outputs.default }}' \
              --argjson f2 '${{ needs.extract-images.outputs.pull }}' \
              '$f2 - $f1' \
          )
          echo "images=${images}" >> "${FORGEJO_OUTPUT}"

          {
              echo "## New images to Pull"
              echo '```json'
              echo "${images}" | jq
              echo '```'
          } >> "${FORGEJO_STEP_SUMMARY}"

  image-pull:
    name: Image Pull
    runs-on: docker
    needs:
      - diff
    strategy:
      matrix:
        image: ${{ fromJSON(needs.diff.outputs.images) }}
      max-parallel: 4
      fail-fast: false
    env:
      MATRIX_IMAGE: ${{ matrix.image }}
    steps:
      - name: Try to pull Image
        run: docker pull "${MATRIX_IMAGE}"

  image-pull-success:
    needs:
      - image-pull
    if: ${{ !cancelled() }}
    name: Image Pull - Success
    runs-on: ubuntu-latest
    steps:
      - name: Any jobs failed?
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1

      - name: All jobs passed or skipped?
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: echo "All jobs passed or skipped" && echo "${{ toJSON(needs.*.result) }}"
