---
model_list:
  - model_name: minimax/MiniMax-M3
    litellm_params:
      model: minimax/MiniMax-M3
      api_key: os.environ/MINIMAX_API_KEY
    model_info:
      mode: chat
      max_input_tokens: 1000000
      supports_function_calling: true
      supports_prompt_caching: true
      supports_vision: true

  - model_name: minimax/MiniMax-M2.7
    litellm_params:
      model: minimax/MiniMax-M2.7
      api_key: os.environ/MINIMAX_API_KEY
    model_info:
      mode: chat
      max_input_tokens: 204800
      supports_function_calling: true
      supports_prompt_caching: true
      supports_vision: false

general_settings:
  health_check_endpoint: /v1/health

router_settings:
  redis_host: os.environ/REDIS_HOST
  redis_port: os.environ/REDIS_PORT
  routing_strategy: simple-shuffle

litellm_settings:
  callbacks:
    - prometheus
  success_callback:
    - prometheus
  failure_callback:
    - prometheus
  prometheus_adapter: true
  require_auth_for_metrics_endpoint: false
  cache: true
  cache_params:
    type: redis
    host: os.environ/REDIS_HOST
    port: os.environ/REDIS_PORT
  drop_params: true
  set_verbose: false
  telemetry: false
  request_timeout: 3600
  num_retries: 1
