---
model_list:
  - model_name: minimax/MiniMax-M3
    litellm_params:
      model: minimax/MiniMax-M3
      api_base: https://api.minimax.io/v1
      api_key: os.environ/MINIMAX_API_KEY
    model_info:
      max_tokens: 1000000
      max_input_tokens: 192000
      max_output_tokens: 16384

  - model_name: minimax/MiniMax-M2.7
    litellm_params:
      model: minimax/MiniMax-M2.7
      api_base: https://api.minimax.io/v1
      api_key: os.environ/MINIMAX_API_KEY
    model_info:
      max_tokens: 204800
      max_input_tokens: 192000
      max_output_tokens: 16384

general_settings:
  health_check_endpoint: /v1/health

router_settings:
  redis_host: os.environ/REDIS_HOST
  redis_port: os.environ/REDIS_PORT
  routing_strategy: simple-shuffle

litellm_settings:
  success_callback: ["prometheus"]
  prometheus_adapter: true
  require_auth_for_metrics_endpoint: false
  cache: true
  cache_params:
    type: redis
    host: os.environ/REDIS_HOST
    port: os.environ/REDIS_PORT
  drop_params: true
  set_verbose: false

environment:
  - MINIMAX_API_KEY
  - REDIS_HOST
  - REDIS_PORT
