---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/litellm.home-operations.com/litellmmcpserver_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMMCPServer
metadata:
  name: context7
spec:
  alias: context7
  url: https://mcp.context7.com/mcp
  transport: http
  authType: bearer_token
  authTokenRef:
    name: context7-mcp-secret
    key: api_key
