---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/mcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: context7-mcp
spec:
  groupRef:
    name: mcp-tools
  image: ghcr.io/stacklok/dockyard/npx/context7:2.2.4
  proxyPort: 8080
  secrets:
    - name: context7-mcp-secret
      key: api_key
      targetEnvName: CONTEXT7_API_KEY
  transport: stdio
