---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sabnzbd
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: sabnzbd
  components:
    - ../../../../components/volsync
    - ../../../../components/kopiur
    - ../../../../components/zeroscaler
  dependsOn:
    - name: volsync
      namespace: system
    - name: openebs
      namespace: openebs
  interval: 1h
  path: "./kubernetes/apps/downloads/sabnzbd/app"
  postBuild:
    substitute:
      APP: sabnzbd
      VOLSYNC_CLAIM: sabnzbd-config
      KOPIUR_CLAIM: sabnzbd-config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: downloads
  timeout: 5m
  wait: false
