---
name: rathole

services:
  rathole-init:
    container_name: rathole-init
    command:
      - /bin/sh
      - -c
      - apk add --no-cache gettext && envsubst < /tmpl/server.toml.tmpl > /config/server.toml.tmp && mv /config/server.toml.tmp /config/server.toml
    environment:
      - RATHOLE_FORGEJO_SSH_TOKEN
    image: docker.io/library/alpine:3.23
    restart: "no"
    volumes:
      - ./config/server.toml.tmpl:/tmpl/server.toml.tmpl:ro
      - rathole-config:/config

  rathole:
    container_name: rathole
    command:
      - --server
      - /etc/rathole/server.toml
    depends_on:
      rathole-init:
        condition: service_completed_successfully
    expose:
      - "22"
      - "2333"
    # renovate: datasource=docker depName=rapiz1/rathole
    image: docker.io/rapiz1/rathole:v0.5.0
    networks:
      default:
        ipv4_address: 172.21.0.2
    restart: unless-stopped
    volumes:
      - rathole-config:/etc/rathole:ro
volumes:
  rathole-config:

networks:
  default:
    name: edge
    external: true
