---
source: file
filenames:
  - /var/log/traefik/access.log
labels:
  type: traefik
---
source: journalctl
journalctl_filter:
  - "--directory=/var/log/host/"
labels:
  type: syslog
---
source: appsec
listen_addr: 0.0.0.0:7422
path: /
appsec_config: crowdsecurity/virtual-patching
labels:
  type: appsec
