---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: publish-k8s-schemas
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: publish-k8s-schemas-secret
    creationPolicy: Owner
    template:
      data:
        GITHUB_TOKEN: "{{ .github_pat_publish_k8s_schemas }}"
  dataFrom:
    - extract:
        key: Github
      rewrite:
        - regexp:
            source: "(.*)"
            target: "github_$1"
