---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: publish-k8s-schemas
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: publish-k8s-schemas-secret
    creationPolicy: Owner
    template:
      data:
        GIT_TOKEN: "{{ .forgejo_lab_assistant_token }}"
  dataFrom:
    - extract:
        key: Forgejo
      rewrite:
        - regexp:
            source: "(.*)"
            target: "forgejo_$1"
