---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wotcher
spec:
  chartRef:
    kind: OCIRepository
    name: wotcher
  interval: 30m
  values:
    controllers:
      wotcher:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            fsGroup: 2000
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 2000
            runAsNonRoot: true
            runAsUser: 2000
        containers:
          app:
            image:
              repository: ghcr.io/bjw-s-labs/wotcher
              tag: 0.0.1@sha256:845c895b29c6ec18f1697c2817363f60a48d4c427bb168952d1972ae3fcf1bbb
            envFrom:
              - secretRef:
                  name: wotcher-secret
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    persistence:
      config:
        type: configMap
        name: wotcher-configmap
        globalMounts:
          - path: /config/config.yaml
            subPath: config.yaml
      data:
        existingClaim: wotcher
        globalMounts:
          - path: /state
            subPath: state
