---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: toolhive-operator-extra-permissions
rules:
  - apiGroups:
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: toolhive-operator-extra-permissions
subjects:
  - kind: ServiceAccount
    name: toolhive-operator
    namespace: ai
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: toolhive-operator-extra-permissions
