---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: konflate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: konflate-secret
    template:
      data:
        KONFLATE_WEBHOOK_SECRET: "{{ .konflate_webhook_secret }}"
        KONFLATE_WRITE_TOKEN: "{{ .forgejo_lab_assistant_token }}"
  dataFrom:
    - extract:
        key: forgejo
      rewrite:
        - regexp:
            source: "(.*)"
            target: "forgejo_$1"
    - extract:
        key: konflate
      rewrite:
        - regexp:
            source: "(.*)"
            target: "konflate_$1"
