{
 "title": "Intel iGPU",
 "tags": [
  "igpu",
  "intel",
  "transcoding"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Instance",
    "query": {
     "query": "label_values({job=\"intel-gpu_exporter\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Render 3D",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "igpu_engines_render_3d_0_busy{instance=~\"${Instance}\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "igpu_engines_render_3d_0_sema{instance=~\"${Instance}\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "igpu_engines_render_3d_0_wait{instance=~\"${Instance}\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Blitter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "igpu_engines_blitter_0_busy{instance=~\"${Instance}\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "igpu_engines_blitter_0_sema{instance=~\"${Instance}\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "igpu_engines_blitter_0_wait{instance=~\"${Instance}\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Video",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "igpu_engines_video_0_busy{instance=~\"${Instance}\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "igpu_engines_video_0_sema{instance=~\"${Instance}\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "igpu_engines_video_0_wait{instance=~\"${Instance}\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Video enhance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "igpu_engines_video_enhance_0_busy{instance=~\"${Instance}\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "igpu_engines_video_enhance_0_sema{instance=~\"${Instance}\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "igpu_engines_video_enhance_0_wait{instance=~\"${Instance}\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "targets": [
    {
     "expr": "igpu_frequency_actual{instance=~\"${Instance}\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "igpu_frequency_requested{instance=~\"${Instance}\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Bandwith",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "igpu_imc_bandwidth_reads{instance=~\"${Instance}\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "igpu_imc_bandwidth_writes{instance=~\"${Instance}\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "iGPU Power",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "igpu_power_package{instance=~\"${Instance}\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "igpu_power_gpu{instance=~\"${Instance}\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "R6 & Interrupts ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "igpu_rc6{instance=~\"${Instance}\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "igpu_interrupts{instance=~\"${Instance}\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Period",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "igpu_period{instance=~\"${Instance}\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}