---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: litellm-secret
    creationPolicy: Owner
    template:
      data:
        LITELLM_MASTER_KEY: "{{ .litellm_master_key }}"
        MINIMAX_API_KEY: "{{ .minimax_api_key }}"
  dataFrom:
    - extract:
        key: litellm
      rewrite:
        - regexp:
            source: "(.*)"
            target: "litellm_$1"
    - extract:
        key: MiniMax
      rewrite:
        - regexp:
            source: "(.*)"
            target: "minimax_$1"
