---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/monitoring.coreos.com/servicemonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: litellm
  labels:
    app.kubernetes.io/instance: litellm
    app.kubernetes.io/name: litellm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: litellm
      app.kubernetes.io/name: litellm
  namespaceSelector:
    matchNames:
      - ai
  targetLabels:
    - app.kubernetes.io/instance
    - app.kubernetes.io/name
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
