---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bonob
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: bonob-secret
    creationPolicy: Owner
    template:
      data:
        BNB_SECRET: "{{ .bonob_encrypt_key }}"
  dataFrom:
    - extract:
        key: bonob
      rewrite:
        - regexp:
            source: "(.*)"
            target: "bonob_$1"
