---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bonob
spec:
  chartRef:
    kind: OCIRepository
    name: bonob
  interval: 30m
  values:
    externalSecrets:
      bonob:
        refreshInterval: 12h
        secretStoreRef:
          kind: ClusterSecretStore
          name: onepassword-connect
        target:
          template:
            data:
              BNB_SECRET: "{{ .bonob_encrypt_key }}"
        dataFrom:
          - extract:
              key: bonob
            rewrite:
              - regexp:
                  source: "(.*)"
                  target: "bonob_$1"
    networkpolicies:
      bonob:
        type: cilium
        egress:
          - toEndpoints:
              - matchLabels:
                  k8s:app.kubernetes.io/controller: navidrome
                  k8s:app.kubernetes.io/instance: navidrome
                  k8s:app.kubernetes.io/name: navidrome
            toPorts:
              - ports:
                  - port: "4533"
                    protocol: TCP
        ingress:
          - fromEndpoints:
              - matchLabels:
                  k8s:io.kubernetes.pod.namespace: network
                  gateway.networking.k8s.io/gateway-name: envoy-external
            toPorts:
              - ports:
                  - port: "4534"
                    protocol: TCP
    controllers:
      bonob:
        pod:
          labels:
            egress.policy.home.arpa/block-all: "true"
          securityContext:
            fsGroup: 65534
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 65534
            runAsNonRoot: true
            runAsUser: 65534
        containers:
          app:
            image:
              repository: ghcr.io/simojenki/bonob
              tag: v0.15.0
            env:
              BNB_PORT: &port 4534
              BNB_SUBSONIC_URL: http://navidrome.media.svc.cluster.local:4533
              BNB_URL: https://bonob.bjw-s.dev
              BNB_LOGIN_THEME: navidrome-ish
            envFrom:
              - externalSecretRef:
                  identifier: bonob
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
            resources:
              requests:
                cpu: 5m
                memory: 64Mi
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    persistence:
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp
    route:
      app:
        hostnames:
          - bonob.bjw-s.dev
        parentRefs:
          - name: envoy-external
            namespace: network
    service:
      app:
        ports:
          http:
            appProtocol: kubernetes.io/wss
            port: *port
