---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grimmory
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: grimmory-secret
    creationPolicy: Owner
  data:
    - secretKey: grimmory_mariadb_password
      remoteRef:
        key: grimmory
        property: mariadb_password
    - secretKey: grimmory_mariadb_root_password
      remoteRef:
        key: grimmory
        property: mariadb_root_password
