---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./backendtrafficpolicy.yaml
  - ./certificate.yaml
  - ./clienttrafficpolicy.yaml
  - ./envoyproxy.yaml
  - ./gatewayclass.yaml
  - ./https-redirect.yaml
  - ./podmonitor.yaml
