---
configs:
  zot_htpasswd:
    environment: ZOT_HTPASSWD
name: zot
networks:
  apps:
    name: apps
    external: true
services:
  zot:
    configs:
      - source: zot_htpasswd
        target: /etc/zot/htpasswd
    container_name: zot
    image: ghcr.io/project-zot/zot-linux-amd64:v2.1.20
    labels:
      dexd.enabled: 'true'
      traefik.enable: 'true'
      traefik.http.routers.zot.rule: Host(`registry.bjw-s.dev`)
      traefik.http.services.zot.loadbalancer.server.port: '5000'
    networks:
      - apps
    restart: unless-stopped
    volumes:
      - ./config/config.json:/etc/zot/config.json:ro
      - data:/var/lib/registry
volumes:
  data:
    driver: local
    driver_opts:
      device: /mnt/tank/apps/zot/data
      o: bind
      type: none
