---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-runner
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: forgejo-runner-secret
    creationPolicy: Owner
    template:
      data:
        token: "{{ .forgejo_runner_k8s_token }}"
        uuid: "{{ .forgejo_runner_k8s_uuid }}"
  dataFrom:
    - extract:
        key: forgejo-runner-k8s
      rewrite:
        - regexp:
            source: "(.*)"
            target: "forgejo_runner_k8s_$1"
