---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bookboss
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: bookboss-secret
    creationPolicy: Owner
    template:
      data:
        BOOKBOSS__ENCRYPTION_SECRET: "{{ .bookboss_encryption_secret }}"
        BOOKBOSS__METADATA__HARDCOVER_API_TOKEN: "{{ .hardcover_api_token }}"
  dataFrom:
    - extract:
        key: bookboss
      rewrite:
        - regexp:
            source: "(.*)"
            target: "bookboss_$1"
    - extract:
        key: Hardcover
      rewrite:
        - regexp:
            source: "(.*)"
            target: "hardcover_$1"
