---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bookboss
spec:
  chartRef:
    kind: OCIRepository
    name: bookboss
  interval: 30m
  values:
    controllers:
      bookboss:
        annotations:
          secret.reloader.stakater.com/reload: bookboss-secret
        pod:
          securityContext:
            fsGroup: 2000
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 2000
            runAsNonRoot: true
            runAsUser: 2000
        containers:
          app:
            image:
              repository: ghcr.io/szinn/bookboss
              tag: v0.8.7
            env:
              BOOKBOSS__DATABASE__DATABASE_URL: sqlite:///data/bookboss.db?mode=rwc
              BOOKBOSS__FRONTEND__BASE_URL: https://bookboss.bjw-s.dev
              BOOKBOSS__LIBRARY__LIBRARY_PATH: /library/books
              BOOKBOSS__IMPORT__BOOKDROP_PATH: /library/bookdrop
              BOOKBOSS__IMPORT__POLL_INTERVAL_SECS: 60
              BOOKBOSS__IMPORT__WORKER_POLL_INTERVAL_SECS: 5
            envFrom:
              - secretRef:
                  name: bookboss-secret
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                spec:
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    persistence:
      data:
        existingClaim: bookboss
        advancedMounts:
          bookboss:
            app:
              - path: /data
                subPath: data
      nfs-nas-media:
        type: nfs
        server: gladius.bjw-s.internal
        path: /mnt/tank/media
        advancedMounts:
          bookboss:
            app:
              - path: /library/books
                subPath: Library/Main/Books/bookboss/books
              - path: /library/bookdrop
                subPath: Library/Main/Books/bookboss/bookdrop
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
    route:
      app:
        hostnames:
          - bookboss.bjw-s.dev
        parentRefs:
          - name: envoy-internal
            namespace: network
    service:
      app:
        ports:
          http:
            port: 8080
