---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/toolhive.stacklok.dev/embeddingserver_v1alpha1.json
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: EmbeddingServer
metadata:
  name: mcp-tools-embedding
spec:
  model: sentence-transformers/all-MiniLM-L6-v2
  image: ghcr.io/huggingface/text-embeddings-inference:cpu-latest@sha256:492506e6a76ce6d0fd834a49f69bee4134f5b37de06052519d358a3d5387434d
  env:
    - name: HOSTNAME
      value: "::"
