---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/toolhive.stacklok.dev/embeddingserver_v1alpha1.json
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: EmbeddingServer
metadata:
  name: mcp-tools-embedding
spec:
  model: sentence-transformers/all-MiniLM-L6-v2
  image: ghcr.io/huggingface/text-embeddings-inference:cpu-latest@sha256:a0d4915c7eefdb566da9ca4d5cb5b27799a6e656773dd87a06196a474c2bbd87
  env:
    - name: HOSTNAME
      value: "::"
  resources:
    limits:
      memory: 347Mi
    requests:
      memory: 347Mi
      cpu: 10m
