---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/toolhive.stacklok.dev/embeddingserver_v1alpha1.json
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: EmbeddingServer
metadata:
  name: mcp-tools-embedding
spec:
  modelCache:
    enabled: true
    size: 5Gi
    storageClassName: openebs-hostpath
