---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-signing-key
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: forgejo-signing-key
    creationPolicy: Owner
    template:
      data:
        ed25519: "{{ .forgejo_signing_private_key }}"
        ed25519.pub: "{{ .forgejo_signing_public_key }}"
  dataFrom:
    - extract:
        key: forgejo
      rewrite:
        - regexp:
            source: "(.*)"
            target: "forgejo_$1"
---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-kanidm-oidc
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: forgejo-kanidm-oidc
    creationPolicy: Owner
    template:
      data:
        key: "{{ .kanidm_forgejo_client_id }}"
        secret: "{{ .kanidm_forgejo_client_secret }}"
  dataFrom:
    - extract:
        key: kanidm
      rewrite:
        - regexp:
            source: "(.*)"
            target: "kanidm_$1"
