---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
spec:
  chartRef:
    kind: OCIRepository
    name: forgejo
  interval: 30m
  values:
    gitea:
      admin:
        username: ""
      config:
        cache:
          ENABLED: true
          ADAPTER: redis
          HOST: redis://forgejo-dragonfly:6379?pool_size=100&idle_timeout=180s
        cron.archive_cleanup:
          ENABLED: true
          RUN_AT_START: true
          SCHEDULE: "@every 1h"
          OLDER_THAN: 2h
        indexer:
          ISSUE_INDEXER_TYPE: bleve
          REPO_INDEXER_ENABLED: true
        lfs:
          PATH: /data/git/lfs
        mailer:
          ENABLED: false
        openid:
          ENABLE_OPENID_SIGNIN: false
          ENABLE_OPENID_SIGNUP: false
        queue:
          TYPE: redis
          CONN_STR: redis://forgejo-dragonfly:6379?pool_size=100&idle_timeout=180s
        repository:
          DEFAULT_REPO_UNITS: repo.code,repo.releases,repo.issues,repo.pulls,repo.actions
          DISABLED_REPO_UNITS: repo.ext_wiki,repo.ext_issues
          ROOT: /data/git/repositories
        repository.pull-request:
          DEFAULT_MERGE_STYLE: squash
        repository.signing:
          FORMAT: ssh
          SIGNING_KEY: /data/signing/ed25519.pub
          SIGNING_NAME: git.bjw-s.dev Instance
          SIGNING_EMAIL: noreply@git.bjw-s.dev
          INITIAL_COMMIT: pubkey
          CRUD_ACTIONS: pubkey, parentsigned
          WIKI: never
          MERGES: pubkey
        security:
          REVERSE_PROXY_TRUSTED_PROXIES: 10.42.0.0/16
        server:
          APP_DATA_PATH: /data/gitea
          ROOT_URL: https://git.bjw-s.dev
          SSH_DOMAIN: git.bjw-s.dev
          SSH_PORT: &sshPort 22
          SSH_SERVER_HOST_KEYS: ssh/ssh_host_ed25519_key
        service:
          ALLOW_ONLY_EXTERNAL_REGISTRATION: true
          DEFAULT_ENABLE_TIMETRACKING: false
          ENABLE_INTERNAL_SIGNIN: false
          ENABLE_PASSWORD_SIGNIN_FORM: false
          SHOW_REGISTRATION_BUTTON: false
        service.explore:
          REQUIRE_SIGNIN_VIEW: true
        session:
          PROVIDER: redis
          PROVIDER_CONFIG: redis://forgejo-dragonfly:6379?pool_size=100&idle_timeout=180s
          SESSION_LIFETIME: 2678400
        webhook:
          ALLOWED_HOST_LIST: "*"
      oauth:
        - name: kanidm
          adminGroup: forgejo_admins@idm.bjw-s.dev
          autoDiscoverUrl: https://idm.bjw-s.dev/oauth2/openid/forgejo/.well-known/openid-configuration
          existingSecret: forgejo-kanidm-oidc
          groupClaimName: groups
          provider: openidConnect
          scopes: profile email groups
    extraContainerVolumeMounts:
      - name: signing-key
        mountPath: /data/signing
        readOnly: true
    extraInitVolumeMounts:
      - name: signing-key
        mountPath: /data/signing
        readOnly: true
    extraVolumes:
      - name: signing-key
        secret:
          secretName: forgejo-signing-key
          defaultMode: 0400
    httpRoute:
      enabled: false
    image:
      rootless: true
      registry: code.forgejo.org
      repository: forgejo/forgejo
      tag: 14.0.4-rootless
    persistence:
      create: false
      claimName: forgejo
    service:
      ssh:
        port: *sshPort
    tcpRoute:
      enabled: true
      parentRefs:
        - name: envoy-external
          namespace: network
          sectionName: ssh
