---
apiVersion: kaniop.rs/v1beta1
kind: KanidmGroup
metadata:
  name: forgejo-admins
spec:
  kanidmRef:
    name: kanidm
    namespace: security
  kanidmName: forgejo_admins
---
apiVersion: kaniop.rs/v1beta1
kind: KanidmGroup
metadata:
  name: forgejo-users
spec:
  kanidmRef:
    name: kanidm
    namespace: security
  kanidmName: forgejo_users
