---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/grafana.integreatly.org/grafana_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: grafana
spec:
  config:
    analytics:
      check_for_updates: "false"
      check_for_plugin_updates: "false"
      feedback_links_enabled: "false"
      reporting_enabled: "false"
    auth:
      disable_login_form: "true"
    auth.basic:
      enabled: "false"
    auth.generic_oauth:
      allow_assign_grafana_admin: "true"
      allow_sign_up: "true"
      auto_login: "true"
      api_url: https://idm.bjw-s.dev/oauth2/openid/grafana/userinfo
      auth_url: https://idm.bjw-s.dev/ui/oauth2
      client_id: $__env{GF_AUTH_GENERIC_OAUTH_CLIENT_ID}
      client_secret: $__env{GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET}
      enabled: "true"
      name: Kanidm
      role_attribute_path: "contains(groups[*], 'grafana_admins@idm.bjw-s.dev') && 'GrafanaAdmin' || 'None'"
      role_attribute_strict: "true"
      scopes: openid profile email groups
      token_url: https://idm.bjw-s.dev/oauth2/token
      use_pkce: "true"
    log:
      mode: console
    metrics:
      enabled: "true"
    news:
      news_feed_enabled: "false"
    plugins:
      plugin_admin_enabled: "false"
    security:
      angular_support_enabled: "true"
    server:
      enable_gzip: "true"
      root_url: https://grafana.bjw-s.dev/
  disableDefaultAdminSecret: true
  disableDefaultSecurityContext: All
  deployment:
    spec:
      strategy:
        type: Recreate
      template:
        spec:
          containers:
            - name: grafana
              env:
                - name: GF_SECURITY_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: grafana-admin-secret
                      key: admin-password
                - name: GF_SECURITY_ADMIN_USER
                  valueFrom:
                    secretKeyRef:
                      name: grafana-admin-secret
                      key: admin-user
                - name: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: grafana-kanidm-oauth2-credentials
                      key: key
                - name: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: grafana-kanidm-oauth2-credentials
                      key: secret
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities:
                  drop:
                    - ALL
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
          volumes:
            - name: grafana-data
              persistentVolumeClaim:
                claimName: grafana-pvc
  httpRoute:
    spec:
      hostnames:
        - grafana.bjw-s.dev
      parentRefs:
        - name: envoy-internal
          namespace: network
  persistentVolumeClaim:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: miroir-local
