---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-automation
components:
  - ../../components/flux-alerts
  - ../../components/kopiur/secret
  - ../../components/namespace
patches:
  - target:
      kind: Namespace
    patch: |
      - op: add
        path: /metadata/labels
        value:
          resource.kubernetes.io/admin-access: "true"
resources:
  - ./bambuddy/ks.yaml
  - ./frigate/ks.yaml
  - ./home-assistant/ks.yaml
