---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ovh-issuer
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: ovh-issuer-secret
    creationPolicy: Owner
  data:
    - secretKey: applicationKey
      remoteRef:
        key: OVHcloud
        property: certmanager-application-key
    - secretKey: applicationSecret
      remoteRef:
        key: OVHcloud
        property: certmanager-application-secret
    - secretKey: consumerKey
      remoteRef:
        key: OVHcloud
        property: certmanager-consumer-key
