---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-webhook-ovh
spec:
  chartRef:
    kind: OCIRepository
    name: cert-manager-webhook-ovh
  interval: 30m
  values:
    groupName: acme.bjw-s.dev
    issuers:
      - name: letsencrypt-production
        create: true
        kind: ClusterIssuer
        acmeServerUrl: https://acme-v02.api.letsencrypt.org/directory
        email: admin@bjw-s.dev
        ovhEndpointName: ovh-eu
        ovhAuthenticationMethod: application
        ovhAuthenticationRef:
          applicationKeyRef:
            name: ovh-issuer-secret
            key: applicationKey
          applicationSecretRef:
            name: ovh-issuer-secret
            key: applicationSecret
          applicationConsumerKeyRef:
            name: ovh-issuer-secret
            key: consumerKey
        profile: shortlived
      - name: letsencrypt-staging
        create: true
        kind: ClusterIssuer
        acmeServerUrl: https://acme-staging-v02.api.letsencrypt.org/directory
        email: admin@bjw-s.dev
        ovhEndpointName: ovh-eu
        ovhAuthenticationMethod: application
        ovhAuthenticationRef:
          applicationKeyRef:
            name: ovh-issuer-secret
            key: applicationKey
          applicationSecretRef:
            name: ovh-issuer-secret
            key: applicationSecret
          applicationConsumerKeyRef:
            name: ovh-issuer-secret
            key: consumerKey
        profile: shortlived
