---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/rbac.authorization.k8s.io/role_v1.json
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-webhook-ovh:secret-reader
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - ovh-issuer-secret
    verbs:
      - get
      - watch
---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/rbac.authorization.k8s.io/rolebinding_v1.json
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-webhook-ovh:secret-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-manager-webhook-ovh:secret-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager-webhook-ovh
