---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/clustersecretstore_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword-connect
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect.external-secrets.svc.cluster.local:8080
      vaults:
        Kubernetes: 1
        Automation: 2
        Services: 3
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-connect-vault-secret
            key: token
            namespace: external-secrets
