---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: externaldns-ovh
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: externaldns-ovh-secret
    creationPolicy: Owner
  data:
    - secretKey: ovh_application_key
      remoteRef:
        key: OVHCloud
        property: external-dns-application-key
    - secretKey: ovh_application_secret
      remoteRef:
        key: OVHCloud
        property: external-dns-application-secret
    - secretKey: ovh_consumer_key
      remoteRef:
        key: OVHCloud
        property: external-dns-consumer-key
