---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: externaldns-ovh
spec:
  chartRef:
    kind: OCIRepository
    name: externaldns-ovh
  interval: 30m
  values:
    fullnameOverride: externaldns-ovh
    logLevel: info
    domainFilters:
      - bjw-s.dev
    env:
      - name: OVH_APPLICATION_KEY
        valueFrom:
          secretKeyRef:
            name: externaldns-ovh-secret
            key: ovh_application_key
      - name: OVH_APPLICATION_SECRET
        valueFrom:
          secretKeyRef:
            name: externaldns-ovh-secret
            key: ovh_application_secret
      - name: OVH_CONSUMER_KEY
        valueFrom:
          secretKeyRef:
            name: externaldns-ovh-secret
            key: ovh_consumer_key
    extraArgs:
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint
      - --gateway-name=envoy-external
    podAnnotations:
      secret.reloader.stakater.com/reload: externaldns-ovh-secret
    policy: sync
    provider:
      name: ovh
    resources:
      requests:
        cpu: 13m
        memory: 42M
      limits:
        memory: 42M
    serviceMonitor:
      enabled: true
    sources:
      - crd
      - gateway-httproute
    triggerLoopOnEvent: true
    txtOwnerId: main
    txtPrefix: "k8s."
