---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
components:
  - ../../components/flux-alerts
  - ../../components/kopiur/secret
  - ../../components/namespace
patches:
  - target:
      kind: Namespace
    patch: |
      - op: add
        path: /metadata/labels
        value:
          resource.kubernetes.io/admin-access: "true"
resources:
  - ./context7-mcp/ks.yaml
  - ./ha-mcp/ks.yaml
  - ./litellm/ks.yaml
  - ./litellm-operator/ks.yaml
  - ./llmkube/ks.yaml
  - ./memini/ks.yaml
  - ./minimax-shim/ks.yaml
  - ./open-webui/ks.yaml
