---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
components:
  - ../../components/flux-alerts
resources:
  - ./context7-mcp/ks.yaml
  - ./namespace.yaml
  - ./ha-mcp/ks.yaml
  - ./litellm/ks.yaml
  - ./minimax-shim/ks.yaml
  - ./open-webui/ks.yaml
  - ./toolhive/ks.yaml
