---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nextcloud
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: nextcloud
  components:
    - ../../../../components/kopiur/backup
    - ../../../../components/dragonfly
  dependsOn:
    - name: kopiur
      namespace: system
    - name: dragonfly-operator
      namespace: database
  interval: 1h
  path: "./kubernetes/apps/selfhosted/nextcloud/app"
  postBuild:
    substitute:
      APP: nextcloud
      KOPIUR_CAPACITY: 15Gi
      KOPIUR_MOVER_UID: "0"
      KOPIUR_MOVER_GID: "82"
      DRAGONFLY_REPLICAS: "1"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: selfhosted
  timeout: 5m
  wait: false
