---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ha-mcp
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: ha-mcp-secret
    creationPolicy: Owner
  data:
    - secretKey: HOMEASSISTANT_TOKEN
      remoteRef:
        key: home-assistant
        property: ha_mcp_token
