---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/mcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: ha-mcp
spec:
  groupRef:
    name: mcp-tools
  env:
    - name: HOMEASSISTANT_URL
      value: http://hestia.bjw-s.internal:8123
  image: ghcr.io/homeassistant-ai/ha-mcp:7.7.0
  podTemplateSpec:
    spec:
      containers:
        - name: mcp
          command:
            - ha-mcp-web
          volumeMounts:
            - mountPath: /tmp
              name: tmpfs
      volumes:
        - name: tmpfs
  secrets:
    - name: ha-mcp-secret
      key: HOMEASSISTANT_TOKEN
  transport: streamable-http
