---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mailkeep
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mailkeep-secret
    creationPolicy: Owner
    template:
      data:
        MAILKEEP__ENCRYPTION_SECRET: "{{ .mailkeep_encryption_secret }}"
  dataFrom:
    - extract:
        key: mailkeep
      rewrite:
        - regexp:
            source: "(.*)"
            target: "mailkeep_$1"
