---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mailkeep
spec:
  chartRef:
    kind: OCIRepository
    name: mailkeep
  interval: 30m
  values:
    externalSecrets:
      mailkeep:
        refreshInterval: 12h
        secretStoreRef:
          kind: ClusterSecretStore
          name: onepassword-connect
        target:
          template:
            data:
              MAILKEEP__ENCRYPTION_SECRET: "{{ .mailkeep_encryption_secret }}"
        dataFrom:
          - extract:
              key: mailkeep
            rewrite:
              - regexp:
                  source: "(.*)"
                  target: "mailkeep_$1"
    networkpolicies:
      mailkeep:
        type: cilium
        endpointSelector:
          matchLabels:
            app.kubernetes.io/name: mailkeep
            app.kubernetes.io/instance: mailkeep
        ingress:
          - fromEndpoints:
              - matchLabels:
                  k8s:io.kubernetes.pod.namespace: network
                  gateway.networking.k8s.io/gateway-name: envoy-internal
            toPorts:
              - ports:
                  - port: "8080"
                    protocol: TCP
    controllers:
      mailkeep:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          labels:
            egress.policy.home.arpa/internet: "true"
          securityContext:
            fsGroup: 2000
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 2000
            runAsNonRoot: true
            runAsUser: 2000
        containers:
          app:
            image:
              repository: ghcr.io/szinn/mailkeep
              tag: v0.1.14@sha256:be7e7833eafe80bef9dc4ae32c9d6aa6a9eccd25cf09d3723885857f9cc971fa
            env:
              MAILKEEP__FRONTEND__BASE_URL: "https://mailkeep.bjw-s.dev"
              MAILKEEP__METADATA_PATH: /data
              MAILKEEP__STORAGE_PATH: /storage
              RUST_LOG: INFO
              TZ: Europe/Amsterdam
            envFrom:
              - externalSecretRef:
                  identifier: mailkeep
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: &port 8080
                  failureThreshold: 3
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /readyz
                    port: *port
                  failureThreshold: 3
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true
    persistence:
      data:
        existingClaim: mailkeep
        globalMounts:
          - path: /data
      storage:
        type: nfs
        server: gladius.bjw-s.internal
        path: /mnt/tank/apps/mailkeep
        globalMounts:
          - path: /storage
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
    route:
      app:
        hostnames:
          - mailkeep.bjw-s.dev
        parentRefs:
          - name: envoy-internal
            namespace: network
    service:
      app:
        ports:
          http:
            port: *port
