---
# yaml-language-server: $schema=https://git.bjw-s.dev/bjw-s/wotcher/raw/commit/96313c482bcfaefb066a83a7ede944c17a004bee/config.schema.json
server:
  interval: "5m"
  state_dir: "/state"

discord:
  webhook_name: wotcher
  default_username: wotcher
  default_avatar_url: ""

destinations:
  bjw-s-releases:
    channel_id: "1399381498095730820"
    type: text
  home-operations-app-template:
    channel_id: "1511472770616131805" # community
    type: forum
    thread_id: "1511771940568698971"
  home-operations-chaski:
    channel_id: "1511467154242011227" # home-operations
    type: forum
    thread_id: "1517988403226873857"
  home-operations-drm-exporter:
    channel_id: "1511467154242011227" # home-operations
    type: forum
    thread_id: "1517150964325421127"
  home-operations-echo:
    channel_id: "1511467154242011227" # home-operations
    type: forum
    thread_id: "1519328323249897593"
  home-operations-external-dns-unifi-webhook:
    channel_id: "1511467154242011227" # home-operations
    type: forum
    thread_id: "1511468785104715846"
  home-operations-flate:
    channel_id: "1511467154242011227" # home-operations
    type: forum
    thread_id: "1511467598087196743"
  home-operations-flux:
    channel_id: "1097927308762939493"
    type: text
  home-operations-gatus-sidecar:
    channel_id: "1511467154242011227" # home-operations
    type: forum
    thread_id: "1511468532859277312"
  home-operations-kguardian:
    channel_id: "1511472770616131805" # community
    type: forum
    thread_id: "1511473620189446265"
  home-operations-konflate:
    channel_id: "1511467154242011227" # home-operations
    type: forum
    thread_id: "1512821036478103592"
  home-operations-kopiur:
    channel_id: "1511467154242011227" # home-operations
    type: forum
    thread_id: "1511469172046041370"
  home-operations-kromgo:
    channel_id: "1511467154242011227" # home-operations
    type: forum
    thread_id: "1511467789733593118"
  home-operations-miroir:
    channel_id: "1511467154242011227" # home-operations
    type: forum
    thread_id: "1517190209786085476"
  home-operations-ocharted:
    channel_id: "1511467154242011227" # home-operations
    type: forum
    thread_id: "1531658804289212527"
  home-operations-renovate-presets:
    channel_id: "1511467154242011227" # home-operations
    type: forum
    thread_id: "1535268278178680913"
  home-operations-talos:
    channel_id: "942576972943491113"
    type: text
  home-operations-tuppr:
    channel_id: "1511467154242011227" # home-operations
    type: forum
    thread_id: "1511468639298256926"
  home-operations-yayamlls:
    channel_id: "1511467154242011227" # home-operations
    type: forum
    thread_id: "1511469075920982237"

repos:
  kguardian-dev/kguardian:
    owner: kguardian-dev
    name: kguardian
    alias: kguardian
    destinations:
      - home-operations-kguardian
    include_prereleases: false
    username: kguardian
    avatar_url: https://avatars.githubusercontent.com/u/121204085?s=200&v=4
    color: "5322961"
    tag_filter: >-
      ^chart\/(?P<version>[v0-9.]+)$

  siderolabs/talos:
    owner: siderolabs
    name: talos
    alias: Talos
    destinations:
      - home-operations-talos
    include_prereleases: false
    username: Talos
    avatar_url: https://avatars.githubusercontent.com/u/13804887?s=200&v=4
    color: "16098851"
    tag_filter: >-
      ^v?\d+\.\d+\.\d+$

  controlplaneio-fluxcd/flux-operator:
    owner: controlplaneio-fluxcd
    name: flux-operator
    alias: Flux Operator
    destinations:
      - home-operations-flux
    include_prereleases: false
    username: Flux Operator
    avatar_url: https://avatars.githubusercontent.com/u/52158677?s=200&v=4
    color: "3612660"

  fluxcd/flux2:
    owner: fluxcd
    name: flux2
    alias: Flux
    destinations:
      - home-operations-flux
    include_prereleases: false
    username: Flux
    avatar_url: https://avatars.githubusercontent.com/u/52158677?s=200&v=4
    color: "3612660"

  bjw-s-labs/app-template:
    owner: bjw-s-labs
    name: helm-charts
    alias: app-template
    destinations:
      - home-operations-app-template
    include_prereleases: false
    username: app-template
    avatar_url: https://avatars.githubusercontent.com/u/6213398?s=200&v=4
    color: "16753920"
    tag_filter: >-
      ^app-template-(?P<version>[v0-9.]+)$

  Hypfer/valetudo:
    owner: Hypfer
    name: valetudo
    alias: Valetudo
    destinations:
      - bjw-s-releases
    include_prereleases: false
    username: valetudo
    avatar_url: https://raw.githubusercontent.com/Hypfer/Valetudo/refs/heads/master/assets/logo/valetudo_logo_small.svg
    color: "1012882"

  home-operations/chaski:
    owner: home-operations
    name: chaski
    alias: chaski
    destinations:
      - home-operations-chaski
    include_prereleases: false
    username: chaski
    avatar_url: https://avatars.githubusercontent.com/u/152294696?s=200&v=4
    color: "4149685"

  home-operations/drm-exporter:
    owner: home-operations
    name: drm-exporter
    alias: drm-exporter
    destinations:
      - home-operations-drm-exporter
    include_prereleases: false
    username: drm-exporter
    avatar_url: https://avatars.githubusercontent.com/u/152294696?s=200&v=4
    color: "4149685"

  home-operations/echo:
    owner: home-operations
    name: echo
    alias: echo
    destinations:
      - home-operations-echo
    include_prereleases: false
    username: echo
    avatar_url: https://avatars.githubusercontent.com/u/152294696?s=200&v=4
    color: "4149685"

  home-operations/external-dns-unifi-webhook:
    owner: home-operations
    name: external-dns-unifi-webhook
    alias: external-dns-unifi-webhook
    destinations:
      - home-operations-external-dns-unifi-webhook
    include_prereleases: false
    username: external-dns-unifi-webhook
    avatar_url: https://avatars.githubusercontent.com/u/152294696?s=200&v=4
    color: "4149685"

  home-operations/flate:
    owner: home-operations
    name: flate
    alias: flate
    destinations:
      - home-operations-flate
    include_prereleases: false
    username: flate
    avatar_url: https://avatars.githubusercontent.com/u/152294696?s=200&v=4
    color: "4149685"

  home-operations/gatus-sidecar:
    owner: home-operations
    name: gatus-sidecar
    alias: gatus-sidecar
    destinations:
      - home-operations-gatus-sidecar
    include_prereleases: false
    username: gatus-sidecar
    avatar_url: https://avatars.githubusercontent.com/u/152294696?s=200&v=4
    color: "4149685"

  home-operations/konflate:
    owner: home-operations
    name: konflate
    alias: konflate
    destinations:
      - home-operations-konflate
    include_prereleases: false
    username: konflate
    avatar_url: https://avatars.githubusercontent.com/u/152294696?s=200&v=4
    color: "4149685"

  home-operations/kopiur:
    owner: home-operations
    name: kopiur
    alias: kopiur
    destinations:
      - home-operations-kopiur
    include_prereleases: false
    username: kopiur
    avatar_url: https://avatars.githubusercontent.com/u/152294696?s=200&v=4
    color: "4149685"

  home-operations/kromgo:
    owner: home-operations
    name: kromgo
    alias: kromgo
    destinations:
      - home-operations-kromgo
    include_prereleases: false
    username: kromgo
    avatar_url: https://avatars.githubusercontent.com/u/152294696?s=200&v=4
    color: "4149685"

  home-operations/miroir:
    owner: home-operations
    name: miroir
    alias: miroir
    destinations:
      - home-operations-miroir
    include_prereleases: false
    username: miroir
    avatar_url: https://avatars.githubusercontent.com/u/152294696?s=200&v=4
    color: "4149685"

  home-operations/ocharted:
    owner: home-operations
    name: ocharted
    alias: ocharted
    destinations:
      - home-operations-ocharted
    include_prereleases: false
    username: ocharted
    avatar_url: https://avatars.githubusercontent.com/u/152294696?s=200&v=4
    color: "4149685"

  home-operations/renovate-presets:
    owner: home-operations
    name: renovate-presets
    alias: renovate-presets
    destinations:
      - home-operations-renovate-presets
    include_prereleases: false
    username: renovate-presets
    avatar_url: https://avatars.githubusercontent.com/u/152294696?s=200&v=4
    color: "4149685"

  home-operations/tuppr:
    owner: home-operations
    name: tuppr
    alias: tuppr
    destinations:
      - home-operations-tuppr
    include_prereleases: false
    username: tuppr
    avatar_url: https://avatars.githubusercontent.com/u/152294696?s=200&v=4
    color: "4149685"

  home-operations/yayamlls:
    owner: home-operations
    name: yayamlls
    alias: yayamlls
    destinations:
      - home-operations-yayamlls
    include_prereleases: false
    username: yayamlls
    avatar_url: https://avatars.githubusercontent.com/u/152294696?s=200&v=4
    color: "4149685"
