---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/grafana.integreatly.org/grafanafolder_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: victoria-logs
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  title: VictoriaLogs
