---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/grafana.integreatly.org/grafanadatasource_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: victoria-logs
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasource:
    type: victoriametrics-logs-datasource
    name: victoria-logs
    access: proxy
    url: http://victoria-logs-server.observability.svc.cluster.local:9428
  plugins:
    - name: victoriametrics-logs-datasource
      version: 0.26.3
