---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/toolhive.stacklok.dev/mcpserver_v1alpha1.json
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: ha-mcp
spec:
  image: ghcr.io/homeassistant-ai/ha-mcp:6.7.0
  transport: streamable-http
  groupRef: mcp-tools
  env:
    - name: HOMEASSISTANT_URL
      value: http://hestia.bjw-s.internal:8123
  secrets:
    - name: ha-mcp-secret
      key: HOMEASSISTANT_TOKEN
  podTemplateSpec:
    spec:
      containers:
        - name: mcp
          command:
            - ha-mcp-web
