# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- minimax-m2-7-anthropic.yaml
- minimax-m2-7.yaml
- minimax-m3-anthropic.yaml
- minimax-m3.yaml
- opencode-go-deepseek-v4-flash.yaml
- opencode-go-glm-5-2.yaml
- opencode-go-kimi-k2-6.yaml
- opencode-go-kimi-k2-7-code.yaml
- opencode-go-mimo-v2-5.yaml
- opencode-go-minimax-m3.yaml
- opencode-go-qwen3-6-plus.yaml
- opencode-go-qwen3-7-max.yaml
