---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./minimax-m2-7.yaml
  - ./minimax-m3.yaml
  - ./minimax-m3-anthropic.yaml
