---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- minimax-m2-7-anthropic.yaml
- minimax-m2-7.yaml
- minimax-m3-anthropic.yaml
- minimax-m3.yaml
- neuralwatt-glm-5-2-fast.yaml
- neuralwatt-glm-5-2-short-fast.yaml
- neuralwatt-glm-5-2-short.yaml
- neuralwatt-glm-5-2.yaml
- neuralwatt-kimi-k2-6-fast.yaml
- neuralwatt-kimi-k2-6.yaml
- neuralwatt-kimi-k2-7-code.yaml
- neuralwatt-qwen3-5-397b-fast.yaml
- neuralwatt-qwen3-5-397b.yaml
- neuralwatt-qwen3-6-35b-fast.yaml
- neuralwatt-qwen3-6-35b.yaml
