---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/litellm.home-operations.com/litellmmodel_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: neuralwatt-glm-5-2-fast
spec:
  modelName: neuralwatt/glm-5.2-fast
  params:
    model: openai/glm-5.2-fast
    apiBase: https://api.neuralwatt.com/v1
    apiKeyRef:
      name: litellm
      key: NEURALWATT_API_KEY
    dropParams: true
    additional:
      temperature: 1.0
  info:
    maxInputTokens: 1048560
    maxOutputTokens: 131072
    supportsFunctionCalling: true
    supportsPromptCaching: true
