---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/litellm.home-operations.com/litellmmodel_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: neuralwatt-kimi-k2-6-flex
spec:
  modelName: neuralwatt/kimi-k2.6-flex
  params:
    model: openai/kimi-k2.6-flex
    apiBase: https://api.neuralwatt.com/v1
    apiKeyRef:
      name: litellm
      key: NEURALWATT_API_KEY
    dropParams: true
  info:
    maxInputTokens: 262128
    maxOutputTokens: 131072
    supportsFunctionCalling: true
    supportsPromptCaching: true
    supportsVision: true
