---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/litellm.home-operations.com/litellmmodel_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: opencode-go-mimo-v2-5
spec:
  modelName: opencode-go/mimo-v2.5
  params:
    model: openai/mimo-v2.5
    apiBase: https://opencode.ai/zen/go/v1
    apiKeyRef:
      name: litellm
      key: OPENCODE_GO_API_KEY
    dropParams: true
  info:
    maxInputTokens: 262144
    maxOutputTokens: 32768
    supportsFunctionCalling: true
    supportsPromptCaching: true
    extra:
      supports_reasoning: true
