---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vmcp-auth-server
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: vmcp-auth-server-secret
    creationPolicy: Owner
    template:
      data:
        signing-key: "{{ .toolhive_auth_server_signing_key }}"
        hmac-key: "{{ .toolhive_auth_server_hmac_key }}"
  dataFrom:
    - extract:
        key: toolhive
      rewrite:
        - regexp:
            source: "(.*)"
            target: "toolhive_$1"
---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vmcp-oidc-client
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: vmcp-oidc-client-secret
    creationPolicy: Owner
    template:
      data:
        client-secret: "{{ .kanidm_toolhive_vmcp_client_secret }}"
  dataFrom:
    - extract:
        key: kanidm
      rewrite:
        - regexp:
            source: "(.*)"
            target: "kanidm_$1"
