---
endpoints:
  - name: icarus | ping
    group: vps
    url: icmp://135.125.53.129
    interval: 1m
    ui:
      hide-url: true
      hide-hostname: true
    conditions:
      - "[CONNECTED] == true"
