---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: woodpecker
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: woodpecker-secret
    creationPolicy: Owner
    template:
      data:
        WOODPECKER_FORGEJO_CLIENT: "{{ .woodpecker_forgejo_client_id }}"
        WOODPECKER_FORGEJO_SECRET: "{{ .woodpecker_forgejo_client_secret }}"
        WOODPECKER_AGENT_SECRET: "{{ .woodpecker_agent_secret }}"
  dataFrom:
    - extract:
        key: Woodpecker
      rewrite:
        - regexp:
            source: "(.*)"
            target: "woodpecker_$1"
