---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: woodpecker
spec:
  chartRef:
    kind: OCIRepository
    name: woodpecker
  interval: 30m
  values:
    server:
      env:
        WOODPECKER_ADMIN: bjw-s
        WOODPECKER_AUTHENTICATE_PUBLIC_REPOS: "true"
        WOODPECKER_DISABLE_USER_AGENT_REGISTRATION: "true"
        WOODPECKER_EXTENSIONS_ALLOWED_HOSTS: private
        WOODPECKER_FORGEJO: "true"
        WOODPECKER_FORGEJO_URL: https://git.bjw-s.dev
        WOODPECKER_HOST: https://ci.bjw-s.dev
      extraSecretNamesForEnvFrom:
        - woodpecker-secret
      extraVolumes:
        - name: woodpecker-data
          persistentVolumeClaim:
            claimName: woodpecker
      extraVolumeMounts:
        - name: woodpecker-data
          mountPath: /var/lib/woodpecker
          subPath: data
      persistentVolume:
        enabled: false
      statefulSet:
        annotations:
          reloader.stakater.com/auto: "true"
    agent:
      env:
        WOODPECKER_BACKEND: kubernetes
        WOODPECKER_BACKEND_K8S_NAMESPACE: dev
        WOODPECKER_BACKEND_K8S_STORAGE_CLASS: openebs-hostpath
        WOODPECKER_BACKEND_K8S_VOLUME_SIZE: 10Gi
        WOODPECKER_CONNECT_RETRY_COUNT: "1"
        WOODPECKER_SERVER: woodpecker-server:9000
        WOODPECKER_MAX_WORKFLOWS: "2"
      extraSecretNamesForEnvFrom:
        - woodpecker-secret
