---
# This file is not managed by doco-cd because it can't manage itself

secrets:
  1pw_token:
    file: /home/truenas_admin/.config/doco-cd/1pw_token
  gh_token:
    file: /home/truenas_admin/.config/doco-cd/gh_token
services:
  app:
    container_name: doco-cd
    environment:
      GIT_ACCESS_TOKEN_FILE: /run/secrets/gh_token
      LOG_LEVEL: info
      POLL_CONFIG: |-
        - url: https://github.com/bjw-s-labs/home-ops.git
          reference: refs/heads/main
          interval: 60
      SECRET_PROVIDER: 1password
      SECRET_PROVIDER_ACCESS_TOKEN_FILE: /run/secrets/1pw_token
      DEPLOY_CONFIG_BASE_DIR: ./docker/truenas/
    healthcheck:
      test:
        - CMD
        - /doco-cd
        - healthcheck
      start_period: 15s
      interval: 30s
      timeout: 5s
      retries: 3
    image: ghcr.io/kimdre/doco-cd:0.72.3@sha256:6afd292a587b280ddd412ab6f3d8d09474db9238a4df9078d5b2c109dc983d87
    restart: unless-stopped
    secrets:
      - 1pw_token
      - gh_token
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
volumes:
  data: {}
