---
working_dir: ./docker/vps-pangolin
auto_discover: true
auto_discover_opts:
  depth: 1
  delete: true
external_secrets:
  MAXMIND_ACCOUNT_ID: op://Services/MaxMind/License Keys/account_id
  MAXMIND_PANGOLIN_LICENSE_KEY: op://Services/MaxMind/License Keys/pangolin_license_key
  PANGOLIN_SERVER_SECRET: op://Services/Pangolin/Server/server_secret
  OVH_APPLICATION_KEY: op://Services/OVHcloud/API Keys/traefik-application-key
  OVH_APPLICATION_SECRET: op://Services/OVHcloud/API Keys/traefik-application-secret
  OVH_CONSUMER_KEY: op://Services/OVHcloud/API Keys/traefik-consumer-key
  CROWDSEC_TRAEFIK_API_KEY: op://Services/Pangolin/Server/crowdsec_traefik_api_key
