---
name: pangolin
services:
  pangolin:
    image: ghcr.io/fosrl/pangolin:1.17.1
    container_name: pangolin
    restart: unless-stopped
    environment:
      - SERVER_SECRET=${PANGOLIN_SERVER_SECRET}
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 256m
    volumes:
      - /opt/pangolin/config:/app/config
    configs:
      - source: pangolin_config
        target: /app/config/config.yml
    healthcheck:
      test:
        - "CMD"
        - "curl"
        - "-f"
        - "http://localhost:3001/api/v1/"
      interval: "10s"
      timeout: "10s"
      retries: 15

  crowdsec:
    container_name: crowdsec
    environment:
      COLLECTIONS: crowdsecurity/traefik crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-generic-rules
      ENROLL_INSTANCE_NAME: pangolin-crowdsec
      ENROLL_TAGS: docker
      GID: "1000"
      PARSERS: crowdsecurity/whitelists
    healthcheck:
      interval: 10s
      retries: 3
      start_period: 30s
      test:
        - CMD
        - cscli
        - lapi
        - status
      timeout: 5s
    image: ghcr.io/crowdsecurity/crowdsec:v1.7.7
    labels:
      - traefik.enable=false
    ports:
      - 6060:6060
    restart: unless-stopped
    volumes:
      - /opt/crowdsec/config:/etc/crowdsec
      - /opt/crowdsec/data:/var/lib/crowdsec/data
      - /opt/pangolin/config/traefik/logs:/var/log/traefik:ro
    configs:
      - source: crowdsec_acquis
        target: /etc/crowdsec/acquis.yaml
      - source: crowdsec_allowlist
        target: /etc/crowdsec/parsers/s02-enrich/my-allowlists.yaml
      - source: crowdsec_ban_ai_crawlers
        target: /etc/crowdsec/scenarios/ban-ai-crawlers.yaml
      - source: crowdsec_ban_asn
        target: /etc/crowdsec/scenarios/ban-asn.yaml

  gerbil:
    image: ghcr.io/fosrl/gerbil:1.3.1
    container_name: gerbil
    restart: unless-stopped
    depends_on:
      pangolin:
        condition: service_healthy
    command:
      - --reachableAt=http://gerbil:3004
      - --generateAndSaveKeyTo=/var/config/key
      - --remoteConfig=http://pangolin:3001/api/v1/
    volumes:
      - /opt/pangolin/config/:/var/config
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - 51820:51820/udp
      - 21820:21820/udp
      - 22:22
      - 443:443
      - 80:80

  traefik:
    image: docker.io/traefik:v3.6
    container_name: traefik
    restart: unless-stopped
    environment:
      - OVH_ENDPOINT=ovh-eu
      - OVH_APPLICATION_KEY=${OVH_APPLICATION_KEY}
      - OVH_APPLICATION_SECRET=${OVH_APPLICATION_SECRET}
      - OVH_CONSUMER_KEY=${OVH_CONSUMER_KEY}
      - CROWDSEC_API_KEY=${CROWDSEC_TRAEFIK_API_KEY}
    network_mode: service:gerbil
    depends_on:
      crowdsec:
        condition: service_healthy
      pangolin:
        condition: service_healthy
    command:
      - --configFile=/etc/traefik/traefik_config.yml
    volumes:
      - /opt/pangolin/config/letsencrypt:/letsencrypt
      - /opt/pangolin/config/traefik/logs:/var/log/traefik
    configs:
      - source: traefik_config
        target: /etc/traefik/traefik_config.yml
      - source: traefik_dynamic_config
        target: /etc/traefik/dynamic_config.yml

  geoipupdate:
    container_name: geoipupdate
    image: ghcr.io/maxmind/geoipupdate:v7.1.1
    restart: unless-stopped
    environment:
      - GEOIPUPDATE_ACCOUNT_ID=${MAXMIND_ACCOUNT_ID}
      - GEOIPUPDATE_LICENSE_KEY=${MAXMIND_PANGOLIN_LICENSE_KEY}
      - GEOIPUPDATE_EDITION_IDS=GeoLite2-Country GeoLite2-ASN
      - GEOIPUPDATE_FREQUENCY=72
    volumes:
      - /opt/pangolin/config/GeoLite2:/usr/share/GeoIP

networks:
  default:
    driver: bridge
    name: pangolin

configs:
  pangolin_config:
    file: ./config/pangolin/config.yaml
  crowdsec_acquis:
    file: ./config/crowdsec/acquis.yaml
  crowdsec_allowlist:
    file: ./config/crowdsec/my_allowlist.yaml
  crowdsec_ban_ai_crawlers:
    file: ./config/crowdsec/ban_ai_crawlers.yaml
  crowdsec_ban_asn:
    file: ./config/crowdsec/ban_asn.yaml
  traefik_config:
    file: ./config/traefik/traefik_config.yaml
  traefik_dynamic_config:
    file: ./config/traefik/dynamic_config.yml
