---
- name: Bootstrap TrueNAS
  hosts: all
  become: true
  gather_facts: false
  vars:
    ansible_user: truenas_admin
    ansible_python_interpreter: auto_silent

  tasks:
    - name: Check host connectivity
      ansible.builtin.ping:

    - name: Read secrets from 1Password
      ansible.builtin.shell: "op read 'op://{{ item.key }}' < /dev/null"
      delegate_to: localhost
      become: false
      loop:
        - key: Shared/c6itdbmw5gdslnnep2vfihhu54/Service accounts/doco-cd
          var: doco_1pw_sa_token
      check_mode: false
      changed_when: false
      no_log: true
      register: secrets_raw

    - name: Set secret facts
      ansible.builtin.set_fact:
        doco_1pw_sa_token: "{{ secrets_raw.results[0].stdout }}"
      no_log: true

    - name: doco-cd
      vars:
        dococd_config_dir: /home/truenas_admin/.config/doco-cd
      block:
        - name: doco-cd | Create directory
          ansible.builtin.file:
            path: "{{ dococd_config_dir }}"
            state: directory
            owner: truenas_admin
            group: truenas_admin
            mode: "0700"

        - name: doco-cd | Copy docker-compose app file
          ansible.builtin.copy:
            src: ../../docker/truenas/.doco-cd/docker-compose.app.yaml
            dest: "{{ dococd_config_dir }}/docker-compose.yaml"
            owner: truenas_admin
            group: truenas_admin
            mode: "0644"
          register: compose_file

        - name: doco-cd | Create secrets
          ansible.builtin.copy:
            dest: "{{ dococd_config_dir }}/{{ item.name }}"
            content: |
              {{ item.content }}
            owner: truenas_admin
            group: truenas_admin
            mode: "0600"
          no_log: true
          loop:
            - name: 1pw_token
              content: "{{ doco_1pw_sa_token }}"

        - name: doco-cd | Run docker-compose
          community.docker.docker_compose_v2:
            project_src: "{{ dococd_config_dir }}"
            files:
              - docker-compose.yaml
            pull: always
            state: present
          when: not ansible_check_mode

        - name: doco-cd | Wait for healthy
          community.docker.docker_container_info:
            name: doco-cd
          register: dococd_info
          until: dococd_info.container.State.Health.Status == "healthy"
          retries: 30
          delay: 10
          when: not ansible_check_mode
