---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: manyfold
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: manyfold
  components:
    - ../../../../components/volsync
    - ../../../../components/kopiur
    - ../../../../components/dragonfly
  dependsOn:
    - name: volsync
      namespace: system
    - name: dragonfly-operator
      namespace: database
  interval: 1h
  path: "./kubernetes/apps/selfhosted/manyfold/app"
  postBuild:
    substitute:
      APP: manyfold
      VOLSYNC_CLAIM: manyfold-data
      KOPIUR_CLAIM: manyfold-data
      VOLSYNC_CAPACITY: 5Gi
      KOPIUR_CAPACITY: 5Gi
      DRAGONFLY_REPLICAS: "1"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: selfhosted
  timeout: 5m
  wait: false
