---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: maintainerr
spec:
  chartRef:
    kind: OCIRepository
    name: maintainerr
  interval: 30m
  values:
    networkpolicies:
      maintainerr:
        type: cilium
        egress:
          - toEndpoints:
              - matchLabels:
                  k8s:app.kubernetes.io/controller: jellyfin
                  k8s:app.kubernetes.io/instance: jellyfin
                  k8s:app.kubernetes.io/name: jellyfin
            toPorts:
              - ports:
                  - port: "8096"
                    protocol: TCP
          - toEndpoints:
              - matchLabels:
                  k8s:io.kubernetes.pod.namespace: downloads
                  k8s:app.kubernetes.io/controller: radarr
                  k8s:app.kubernetes.io/instance: radarr
                  k8s:app.kubernetes.io/name: radarr
            toPorts:
              - ports:
                  - port: "7878"
                    protocol: TCP
          - toEndpoints:
              - matchLabels:
                  k8s:io.kubernetes.pod.namespace: downloads
                  k8s:app.kubernetes.io/controller: sonarr
                  k8s:app.kubernetes.io/instance: sonarr
                  k8s:app.kubernetes.io/name: sonarr
            toPorts:
              - ports:
                  - port: "8989"
                    protocol: TCP
        ingress:
          - fromEndpoints:
              - matchLabels:
                  k8s:io.kubernetes.pod.namespace: network
                  gateway.networking.k8s.io/gateway-name: envoy-internal
            toPorts:
              - ports:
                  - port: "6246"
                    protocol: TCP
    controllers:
      maintainerr:
        pod:
          labels:
            egress.policy.home.arpa/internet: "true"
          securityContext:
            fsGroup: 2000
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 2000
            runAsNonRoot: true
            runAsUser: 2000
        containers:
          app:
            image:
              repository: ghcr.io/maintainerr/maintainerr
              tag: 3.29.0@sha256:7487d374290e59add65407ec295629e489f9057dbf18e2a9dff70d6201ffb6f9
            env:
              TELEMETRY: "off"
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 5m
                memory: 128Mi
              limits:
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              # readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    persistence:
      config:
        existingClaim: maintainerr
        advancedMounts:
          maintainerr:
            app:
              - path: /opt/data
                subPath: data
    route:
      app:
        hostnames:
          - maintainerr.bjw-s.dev
        parentRefs:
          - name: envoy-internal
            namespace: network
    service:
      app:
        ports:
          http:
            port: 6246
