---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: miroir
spec:
  chartRef:
    kind: OCIRepository
    name: miroir
  interval: 30m
  values:
    nodes:
      delta:
        backend: zfs
        zfsDataset: data-pool/miroir
    storageClass:
      create: true
      name: miroir-local
      isDefault: true
    replicatedStorageClass:
      create: true
      name: miroir-replicated
      isDefault: false
      quorum: last-man-standing
    volumeSnapshotClass:
      create: true
      name: miroir-snap
