---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kguardian-db
  namespace: kguardian
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: miroir-local
