---
customization:
  extraKernelArgs:
    - initcall_blacklist=algif_aead_init # copy.fail fix
  systemExtensions:
    officialExtensions:
      - siderolabs/drbd
      - siderolabs/i915
      - siderolabs/intel-ucode
