---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kopiur.home-operations.com/clusterrepository_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: ClusterRepository
metadata:
  name: nas
spec:
  allowedNamespaces:
    all: true
  backend:
    filesystem:
      path: /repo
      volume:
        nfs:
          path: /mnt/drone/backup/kopiur
          server: gladius.bjw-s.internal
  encryption:
    passwordSecretRef:
      name: kopiur-nas-secret
      namespace: system
      key: KOPIA_PASSWORD
  identityDefaults:
    hostnameExpr: namespace
    usernameExpr: policyName
  maintenance:
    schedule:
      quick:
        cron: 0 * * * *
        jitter: 10m
      full:
        cron: 0 3 * * *
        jitter: 1h
  parameters:
    epoch:
      minDuration: 1h
  scheduleDefaults:
    timezone: Europe/Amsterdam
