---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/toolhive.stacklok.dev/mcpserver_v1alpha1.json
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: memory-mcp
spec:
  groupRef:
    name: mcp-tools
  image: ghcr.io/bjw-s-labs/mcp-memory:2026.1.26@sha256:df4a7e3709dfe363cd9048df13b2aed7f13ee135f07d07cd318d69f7e058abd8
  podTemplateSpec:
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: memory-mcp
      containers:
        - name: mcp
          volumeMounts:
            - name: data
              mountPath: /data
  transport: stdio
