---
apiVersion: kaniop.rs/v1beta1
kind: Kanidm
metadata:
  name: sso
spec:
  domain: idm.bjw-s.dev
  origin: https://idm.bjw-s.dev
  replicaGroups:
    - name: default
      replicas: 1
      primaryNode: true
      resources:
        requests:
          cpu: 10m
        limits:
          memory: 512Mi
  image: kanidm/server:1.11.2
  logLevel: info
  groupNamespaceSelector: {}
  oauth2ClientNamespaceSelector: {}
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: miroir-local
  tlsSecretName: idm-bjw-s-dev-tls
  gateway:
    parentRefs:
      - name: envoy-external
        namespace: network
    hostnames:
      - idm.bjw-s.dev
    backendTlsPolicy:
      validation:
        hostname: idm.bjw-s.dev
        wellKnownCaCertificates: System
