---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: sso-admin
spec:
  data:
    - match:
        secretKey: ADMIN_USERNAME
        remoteRef:
          remoteKey: Kanidm (admin)
          property: username
    - match:
        secretKey: ADMIN_PASSWORD
        remoteRef:
          remoteKey: Kanidm (admin)
          property: password
    - match:
        secretKey: IDM_ADMIN_USERNAME
        remoteRef:
          remoteKey: Kanidm (idm_admin)
          property: username
    - match:
        secretKey: IDM_ADMIN_PASSWORD
        remoteRef:
          remoteKey: Kanidm (idm_admin)
          property: password
  secretStoreRefs:
    - name: onepassword-connect
      kind: ClusterSecretStore
  selector:
    secret:
      name: sso-admin-passwords
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: zot-kanidm-oauth2-credentials
spec:
  data:
    - match:
        secretKey: CLIENT_ID
        remoteRef:
          remoteKey: Kanidm - Zot
          property: client_id
      metadata:
        apiVersion: kubernetes.external-secrets.io/v1alpha1
        kind: PushSecretMetadata
        spec:
          vault: Infrastructure - Automation
    - match:
        secretKey: CLIENT_SECRET
        remoteRef:
          remoteKey: Kanidm - Zot
          property: client_secret
      metadata:
        apiVersion: kubernetes.external-secrets.io/v1alpha1
        kind: PushSecretMetadata
        spec:
          vault: Infrastructure - Automation
  secretStoreRefs:
    - name: onepassword-connect
      kind: ClusterSecretStore
  selector:
    secret:
      name: zot-kanidm-oauth2-credentials
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: garage-ui-kanidm-oauth2-credentials
spec:
  data:
    - match:
        secretKey: CLIENT_ID
        remoteRef:
          remoteKey: Kanidm - Garage UI
          property: client_id
      metadata:
        apiVersion: kubernetes.external-secrets.io/v1alpha1
        kind: PushSecretMetadata
        spec:
          vault: Infrastructure - Automation
    - match:
        secretKey: CLIENT_SECRET
        remoteRef:
          remoteKey: Kanidm - Garage UI
          property: client_secret
      metadata:
        apiVersion: kubernetes.external-secrets.io/v1alpha1
        kind: PushSecretMetadata
        spec:
          vault: Infrastructure - Automation
  secretStoreRefs:
    - name: onepassword-connect
      kind: ClusterSecretStore
  selector:
    secret:
      name: garage-ui-kanidm-oauth2-credentials
