---
working_dir: ./docker/truenas
auto_discover: true
auto_discover_opts:
  depth: 1
  delete: true
external_secrets:
  OVH_APPLICATION_KEY: op://Services/OVHcloud/API Keys/traefik-application-key
  OVH_APPLICATION_SECRET: op://Services/OVHcloud/API Keys/traefik-application-secret
  OVH_CONSUMER_KEY: op://Services/OVHcloud/API Keys/traefik-consumer-key
