---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: ${APP}-anubis
  name: ${APP}-anubis-policy
data:
  policy.yaml: |-
    bots:
      - import: (data)/apps/gitea-rss-feeds.yaml
      - import: (data)/clients/git.yaml
      - import: (data)/clients/docker-client.yaml
      - name: allow-api
        path_regex: ^/api/.*
        action: ALLOW
      - import: (data)/meta/default-config.yaml
    dnsbl: false
