---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: nextcloud-secret
    creationPolicy: Owner
    template:
      data:
        nextcloud-username: "{{ .nextcloud_username }}"
        nextcloud-password: "{{ .nextcloud_password }}"
  dataFrom:
    - extract:
        key: Nextcloud (Admin)
      rewrite:
        - regexp:
            source: "(.*)"
            target: "nextcloud_$1"
