---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
spec:
  chartRef:
    kind: OCIRepository
    name: nextcloud
  interval: 30m
  values:
    cronjob:
      enabled: true
      type: cronjob
      cronjob:
        successfulJobsHistoryLimit: 1
        securityContext:
          runAsGroup: 1022
          runAsNonRoot: true
          runAsUser: 1022
    image:
      flavor: fpm-alpine
    nginx:
      enabled: true
    nextcloud:
      datadir: /var/www/data
      existingSecret:
        enabled: true
        secretName: nextcloud-secret
        usernameKey: nextcloud-username
        passwordKey: nextcloud-password
      host: &host files.bjw-s.dev
      mail:
        enabled: false
      securityContext:
        runAsGroup: 1022
        runAsNonRoot: true
        runAsUser: 1022
      configs:
        proxy.config.php: |-
          <?php
          $CONFIG = array (
            'check_data_directory_permissions' => false,
            'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
            'mail_smtpmode' => 'null',
            'skeletondirectory' => '',
            'trusted_proxies' => array(
              0 => '127.0.0.1',
              1 => '10.244.0.0/16',
            ),
          ); ?>
        misc.config.php: |-
          <?php
          $CONFIG = array (
            'default_phone_region' => 'NL',
            'maintenance_window_start' => 2,
          ); ?>
    httpRoute:
      enabled: true
      hostnames:
        - *host
      parentRefs:
        - name: envoy-internal
          namespace: network
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: "/"
          filters:
            - type: ResponseHeaderModifier
              responseHeaderModifier:
                add:
                  - name: strict-transport-security
                    value: max-age=31536000
    persistence:
      enabled: true
      existingClaim: nextcloud
    redis:
      enabled: true
      architecture: standalone
