metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "lmdb"

replication_factor = 1

rpc_bind_addr = "[::]:9001"

[s3_api]
s3_region = "us-east-1"
api_bind_addr = "[::]:9000"

[admin]
api_bind_addr = "[::]:9002"
