---
networks:
  apps:
    name: apps
    external: true
services:
  garage:
    command:
      - /garage
      - '-c'
      - /etc/garage/garage.toml
      - server
    container_name: garage
    environment:
      GARAGE_ADMIN_TOKEN: ${GARAGE_ADMIN_TOKEN}
      GARAGE_RPC_SECRET: ${GARAGE_RPC_SECRET}
    image: docker.io/dxflrs/garage:v2.3.0
    labels:
      dexd.enabled: 'true'
      traefik.enable: 'true'
      traefik.http.routers.garage-s3.rule: Host(`s3.bjw-s.dev`)
      traefik.http.services.garage-s3.loadbalancer.server.port: '9000'
    networks:
      - apps
    restart: unless-stopped
    user: '3000:4000'
    volumes:
      - ./config/garage.toml:/etc/garage/garage.toml:ro
      - meta:/var/lib/garage/meta
      - data:/var/lib/garage/data
  garage-ui:
    container_name: garage-ui
    environment:
      GARAGE_UI_AUTH_OIDC_ADMIN_ROLE: garage-users@idm.bjw-s.dev
      GARAGE_UI_AUTH_OIDC_CLIENT_ID: ${GARAGE_UI_OIDC_CLIENT_ID}
      GARAGE_UI_AUTH_OIDC_CLIENT_SECRET: ${GARAGE_UI_OIDC_CLIENT_SECRET}
      GARAGE_UI_AUTH_OIDC_COOKIE_SECURE: 'true'
      GARAGE_UI_AUTH_OIDC_ENABLED: 'true'
      GARAGE_UI_AUTH_OIDC_ISSUER_URL: https://idm.bjw-s.dev/oauth2/openid/garage-ui
      GARAGE_UI_AUTH_OIDC_PROVIDER_NAME: Kanidm
      GARAGE_UI_AUTH_OIDC_ROLE_ATTRIBUTE_PATH: groups
      GARAGE_UI_AUTH_OIDC_SCOPES: 'openid email profile groups'
      GARAGE_UI_GARAGE_ADMIN_ENDPOINT: http://garage:9002
      GARAGE_UI_GARAGE_ADMIN_TOKEN: ${GARAGE_ADMIN_TOKEN}
      GARAGE_UI_GARAGE_ENDPOINT: http://garage:9000
      GARAGE_UI_GARAGE_REGION: us-east-1
      GARAGE_UI_SERVER_DOMAIN: garage.bjw-s.dev
      GARAGE_UI_SERVER_ENVIRONMENT: production
      GARAGE_UI_SERVER_HOST: 0.0.0.0
      GARAGE_UI_SERVER_PORT: 8080
      GARAGE_UI_SERVER_ROOT_URL: https://garage.bjw-s.dev
    image: docker.io/noooste/garage-ui:v0.12.1
    labels:
      dexd.enabled: 'true'
      traefik.enable: 'true'
      traefik.http.routers.garage-ui.rule: Host(`garage.bjw-s.dev`)
      traefik.http.services.garage-ui.loadbalancer.server.port: '8080'
    networks:
      - apps
    restart: unless-stopped
volumes:
  data:
    driver: local
    driver_opts:
      device: /mnt/tank/apps/garage/data
      o: bind
      type: none
  meta:
    driver: local
    driver_opts:
      device: /mnt/tank/apps/garage/meta
      o: bind
      type: none
