---
type: trigger
name: custom/ban-asn
description: "Ban traffic from AS numbers"
filter: >-
  evt.Meta.ASNumber in [
    "32934"
  ]
groupby: evt.Meta.source_ip
blackhole: 5m
labels:
  remediation: true
  type: ban
