---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: litellm-operator
spec:
  chartRef:
    kind: OCIRepository
    name: litellm-operator
  interval: 30m
  values:
    controller:
      leaderElection:
        enabled: true
    webhook:
      enabled: true
    llmkube:
      autoRegister: true
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        memory: 128Mi
