---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: litellm-operator-extra-permissions
rules:
  - apiGroups:
      - litellm.home-operations.com
    resources:
      - litellmteams
      - litellmvirtualkeys
    verbs:
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: litellm-operator-extra-permissions
subjects:
  - kind: ServiceAccount
    name: litellm-operator
    namespace: ai
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: litellm-operator-extra-permissions
