---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-webui
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: open-webui-secret
    creationPolicy: Owner
    template:
      data:
        OAUTH_CLIENT_ID: "{{ .kanidm_openwebui_client_id }}"
        OAUTH_CLIENT_SECRET: "{{ .kanidm_openwebui_client_secret }}"
        WEBUI_SECRET_KEY: "{{ .openwebui_secret_key }}"
  dataFrom:
    - extract:
        key: kanidm
      rewrite:
        - regexp:
            source: "(.*)"
            target: "kanidm_$1"
    - extract:
        key: open-webui
      rewrite:
        - regexp:
            source: "(.*)"
            target: "openwebui_$1"
