---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/cilium.io/ciliumcidrgroup_v2.json
apiVersion: cilium.io/v2
kind: CiliumCIDRGroup
metadata:
  name: nas
spec:
  externalCIDRs:
    - 10.1.1.12/32
